/*
** EPITECH PROJECT, 2023
** sfml_test
** File description:
** std
*/

#ifndef STD_H_
#define STD_H_

#include <iostream>
#include <string>
#include <sstream>
#include <fstream>
#include <vector>
#include <map>
#include <list>
#include <algorithm>
#include <memory>
#include <chrono>
#include <thread>
#include <cmath>
#include <ctime>
#include <cstdlib>
#include <iomanip>
#include <random>
#include <functional>
#include <utility>
#include <cctype>
#include <locale>
#include <codecvt>
#include <regex>
#include <type_traits>
#include <iterator>
#include <mutex>
#include <condition_variable>
#include <atomic>
#include <future>
#include <initializer_list>
#include <stdexcept>
#include <cassert>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <cwchar>
#include <cwctype>
#include <cinttypes>
#include <cuchar>
#include <cfloat>
#include <climits>
#include <clocale>
#include <limits>
#include <new>
#include <unordered_map>
#include <unordered_set>
#include <stack>
#include <queue>
#include <deque>
#include <array>
#include <bitset>
#include <tuple>
#include <typeinfo>
#include <typeindex>
#include <exception>
#include <initializer_list>
#include <stdexcept>
#include <system_error>
#include <ios>
#include <iosfwd>
#include <istream>
#include <ostream>
#include <sys/ptrace.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <sys/user.h>
#include <iostream>
#include <vector>
#include <string>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <sys/user.h>
#include <unistd.h>
#include <thread>
#include <unordered_set>

#endif /* !STD_H_ */
